### ISSUE TITLE
Demo in readme failing with ClassNotFoundException

### ISSUE THREAD

**Issue by sanity** [sanity/Swarm#20]
Paul, would you mind looking into this as I'm not very familiar with sbt, and I'm still refreshing my memory about Scala (I've been in Kotlin-land for the last year ;).

Here is the output from sbt when I attempt to launch swarm.demos.Listen, I'm following the instructions in the main readme verbatim:

```
ian@vega-4 /t/Swarm:master> sbt/sbt "demos/run-main swarm.demos.Listen"                                                        13-08-18 11:38:23
[info] Loading project definition from /private/tmp/Swarm/project
[info] Updating {file:/private/tmp/Swarm/project/}default-3203b0...
[info] Resolving org.scala-sbt#precompiled-2_10_1;0.12.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/Swarm/project/target/scala-2.9.2/sbt-0.12/classes...
[info] Set current project to core (in build file:/private/tmp/Swarm/)
[info] Updating {file:/private/tmp/Swarm/}core...
[info] Resolving org.scala-lang#scala-reflect;2.10.1 ...
[info] Done updating.
[info] Updating {file:/private/tmp/Swarm/}demos...
[info] Resolving org.scala-lang#scala-reflect;2.10.1 ...
[info] Done updating.
[info] Compiling 10 Scala sources to /private/tmp/Swarm/swarm-core/target/scala-2.10/classes...
[warn] /private/tmp/Swarm/swarm-core/src/main/scala/swarm/Swarm.scala:149: expression matchEnd5(x: Unit){
[warn]   x
[warn] } is cps-transformed unexpectedly
[warn]     xs match {
[warn]     ^
[warn] /private/tmp/Swarm/swarm-core/src/main/scala/swarm/Swarm.scala:152: a pure expression does nothing in statement position; you may be omitting necessary parentheses
[warn]         f(x)
[warn]          ^
[warn] there were 7 feature warning(s); re-run with -feature for details
[warn] three warnings found
[info] Compiling 5 Scala sources to /private/tmp/Swarm/swarm-demos/target/scala-2.10/classes...
[info] Running swarm.demos.Listen
[error] (run-main) java.lang.ClassNotFoundException: swarm.demos.Listen
java.lang.ClassNotFoundException: swarm.demos.Listen
    at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:261)
[trace] Stack trace suppressed: run last demos/compile:run-main for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last demos/compile:run-main for the full output.
[error] (demos/compile:run-main) Nonzero exit code: 1
[error] Total time: 16 s, completed Aug 18, 2013 11:38:54 AM
```

**Comment by bitwalker** [comment]
Everything resides under the new org.swarmframework namespace now, I just forgot to update the README, sorry about that!

See e079c58 for the changes.
