### ISSUE TITLE
Exception when I click on a sample user in Twitter demo

### ISSUE THREAD

**Issue by sanity** [sanity/Swarm#4]
Another snag...

java.lang.NoClassDefFoundError: swarm/twitter/SwarmBridge$
    at swarm.twitter.SwarmTwitterTemplate$$anonfun$3.apply(SwarmTwitterTemplate.scala:73)
    at org.scalatra.ScalatraKernel$Route$$anonfun$org$scalatra$ScalatraKernel$Route$$invokeAction$1.apply(ScalatraKernel.scala:78)
    at org.scalatra.ScalatraKernel$Route$$anonfun$org$scalatra$ScalatraKernel$Route$$invokeAction$1.apply(ScalatraKernel.scala:77)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalatra.ScalatraKernel$Route.org$scalatra$ScalatraKernel$Route$$invokeAction(ScalatraKernel.scala:76)
    at org.scalatra.ScalatraKernel$Route$$anonfun$apply$1.apply(ScalatraKernel.scala:73)
    at org.scalatra.ScalatraKernel$Route$$anonfun$apply$1.apply(ScalatraKernel.scala:73)
    at scala.Option.flatMap(Option.scala:147)
    at org.scalatra.ScalatraKernel$Route.apply(ScalatraKernel.scala:73)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$7.apply(ScalatraKernel.scala:137)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2$$anonfun$7.apply(ScalatraKernel.scala:137)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:209)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply$mcV$sp(ScalatraKernel.scala:137)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ScalatraKernel.scala:134)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$2.apply(ScalatraKernel.scala:134)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ScalatraKernel.scala:134)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1.apply(ScalatraKernel.scala:134)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1$$anonfun$apply$mcV$sp$1.apply(ScalatraKernel.scala:134)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1.apply$mcV$sp(ScalatraKernel.scala:133)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1.apply(ScalatraKernel.scala:133)
    at org.scalatra.ScalatraKernel$$anonfun$handle$1.apply(ScalatraKernel.scala:133)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    at org.scalatra.ScalatraKernel$class.handle(ScalatraKernel.scala:132)
    at org.scalatra.ScalatraServlet.handle(ScalatraServlet.scala:11)
    at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:18)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by earldouglas** [comment]
Seems like a class in swarm-twitter didn't get compiled.  I'll check it out.

**Comment by earldouglas** [comment]
From a clean system, I was able to use the Twitter example with the steps now outlined here: https://github.com/sanity/Swarm/blob/master/README.rst

What version of sbt are you running?  Did you notice any compilation warnings (or similar)?

**Comment by sanity** [comment]
Here is the build output: https://gist.github.com/02b1cb84451021153e20

And here is what sbt prints on startup:

```
Swarm  master $ sbt
[info] Building project swarm 1.0-SNAPSHOT against Scala 2.9.0
[info]    using SwarmProject with sbt 0.7.7 and Scala 2.7.7
```

I'll try starting fresh.

**Comment by sanity** [comment]
Ok, its working now that I'm starting fresh (with a minor edit to the README file, which I've committed).  Closing.
